export default [
    {
        name: "base",
        data: {},
        items: [
            {
                name: "topChairModel",
                source: "/assets/models/topChair.glb",
                type: "model",
            },
            { name: "rubiksCube", source: "/assets/models/Rubik.glb" },
            {
                name: "skyTexture",
                source: "/assets/textures/skyTexture.ktx2",
                type: "texture",
            },
            {
                name: "perlin",
                source: "/assets/textures/perlin.png",
                type: "texture",
            },
            {
                name: "baked1",
                source: "/assets/textures/baked1.ktx2",
                type: "texture",
            },
            {
                name: "baked2",
                source: "/assets/textures/baked2.ktx2",
                type: "texture",
            },
            {
                name: "baked3",
                source: "/assets/textures/baked3.ktx2",
                type: "texture",
            },
            {
                name: "texture_paint",
                source: "/assets/textures/texture_paint.png",
                type: "texture",
            },
            { name: "_roomModel", source: "/assets/models/room.glb" },
            { name: "_roomModel2", source: "/assets/models/room2.glb" },
            { name: "_roomModel3", source: "/assets/models/room3.glb" },
            { name: "whiteboard", source: "/assets/models/whiteboard.glb" },
            { name: "leftMonitor", source: "/assets/models/leftMonitor.glb" },
            { name: "rightMonitor", source: "/assets/models/rightMonitor.glb" },
            { name: "linkedin", source: "/assets/models/linkedin.glb" },
            { name: "github", source: "/assets/models/github.glb" },
            { name: "mail", source: "/assets/models/mail.glb" },
            {
                name: "cubeTexture",
                source: [
                    "/assets/environmentMaps/nx.jpg",
                    "/assets/environmentMaps/ny.jpg",
                    "/assets/environmentMaps/nz.jpg",
                    "/assets/environmentMaps/px.jpg",
                    "/assets/environmentMaps/py.jpg",
                    "/assets/environmentMaps/pz.jpg",
                ],
                type: "cubeTexture",
            },
            { name: "markerOpen", source: "/assets/sounds/marker-open.mp3" },
            { name: "eraser", source: "/assets/sounds/eraser.mp3" },
            { name: "confetti", source: "/assets/sounds/confetti.mp3" },
            { name: "partyblower", source: "/assets/sounds/partyblower.mp3" },
            { name: "mouseclick", source: "/assets/sounds/mouseclick.ogg" },
            { name: "mouserelease", source: "/assets/sounds/mouserelease.ogg" },
            { name: "rubik_1", source: "/assets/sounds/rubik_1.mp3" },
            { name: "rubik_2", source: "/assets/sounds/rubik_2.mp3" },
            { name: "rubik_3", source: "/assets/sounds/rubik_3.mp3" },
            { name: "whoosh", source: "/assets/sounds/whoosh.mp3" },
            { name: "select1", source: "/assets/sounds/select1.ogg" },
            { name: "select2", source: "/assets/sounds/select2.ogg" },
            { name: "screenshot", source: "/assets/social/screenshot.png" },
        ],
    },
];